apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
      type: app
      service: mysql
spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
        type: app
        service: mysql
    type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        type: app
        service: mysql
spec:
    selector:
        matchLabels:
            type: app
            service: mysql
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                type: app
                service: mysql
        spec:
            containers:
            - image: mysql-image
              imagePullPolicy: Never
              name: mysql-container
              livenessProbe:
                initialDelaySeconds: 20
                periodSeconds: 10
                timeoutSeconds: 5
                tcpSocket:
                  port: 3306
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: password
              volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
            volumes:
            - name: mysql-persistent-storage
              persistentVolumeClaim:
                  claimName: mysql-pv-claim
