apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    type: app
    service: grafana
spec:
  selector:
    matchLabels:
      type: app
      service: grafana
  minReadySeconds: 5
  template:
    metadata:
      labels:
        type: app
        service: grafana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel, blackmirror1-singlestat-math-panel
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        image: grafana-image
        imagePullPolicy: Never
        name: grafana
        volumeMounts:
        - mountPath: /etc/grafana/provisioning
          name: grafana-volume
          subPath: provisioning/
        - mountPath: /var/lib/grafana/dashboards
          name: grafana-volume
          subPath: dashboards/
        - mountPath: /etc/grafana/grafana.ini
          name: grafana-volume
          subPath: grafana.ini
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: grafana-volume
        hostPath:
          path: /grafana
---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    type: app
    service: grafana
spec:
  selector:
    type: app
    service: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
