apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    type: app
    service: grafana
spec:
  selector:
    matchLabels:
      type: app
      service: grafana
  minReadySeconds: 5
  template:
    metadata:
      labels:
        type: app
        service: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana-image
        imagePullPolicy: Never
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          tcpSocket:
            port: 3000
        ports:
        - containerPort: 3000
          name: grafana
          protocol: TCP
        env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel, blackmirror1-singlestat-math-panel
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin

---


apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    type: app
    service: grafana
spec:
  selector:
    type: app
    service: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
