apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: app
    service: nginx
spec:
  selector:
    matchLabels:
        type: app
        service: nginx
  template:
    metadata:
      labels:
          type: app
          service: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx-image
        imagePullPolicy: Never
        livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            tcpSocket:
                port: 22
        ports:
            - containerPort: 80 
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 22 
              name: ssh
              protocol: TCP
#volumeMounts:
#- name: nginx-conf-volume
#mountPath: /etc/nginx/conf.d/
#volumes:
#- name: nginx-conf-volume
#configMap:
#name: nginx-conf

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: nginx-service
  labels:
    type: app
    service: nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
      type: app
      service: nginx
