apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-service
    labels:
      type: app
      service: phpmyadmin
spec:
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
        type: app
        service: phpmyadmin
    type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin-deployment
    labels:
        type: app
        service: phpmyadmin
spec:
    selector:
        matchLabels:
            type: app
            service: phpmyadmin
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                type: app
                service: phpmyadmin
        spec:
            containers:
            - image: phpmyadmin-image
              imagePullPolicy: Never
              name: phpmyadmin-container
              ports:
              - containerPort: 5000
              livenessProbe:
                httpGet:
                  port: 5000
                initialDelaySeconds: 5
                periodSeconds: 5
              volumeMounts:
              - name: phpmyadmin-pv
                mountPath: /var/www/html/phpmyadmin
            volumes:
            - name: phpmyadmin-pv
              persistentVolumeClaim:
                claimName: phpmyadmin-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    type: app
    service: phpmyadmin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
