apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
    labels:
      type: app
      service: wordpress
spec:
    ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050
    selector:
        type: app
        service: wordpress
    type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-deployment
    labels:
        type: app
        service: wordpress
spec:
    selector:
        matchLabels:
            type: app
            service: wordpress
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                type: app
                service: wordpress
        spec:
            containers:
            - image: wordpress-image
              imagePullPolicy: Never
              name: wordpress-container
              ports:
              - containerPort: 5050
              livenessProbe:
                httpGet:
                  port: 5050
                initialDelaySeconds: 5
                periodSeconds: 5
