apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf-deployment
    labels:
        type: app
        service: telegraf
spec:
    selector:
        matchLabels:
            type: app
            service: telegraf
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                type: app
                service: telegraf
        spec:
            containers:
            - image: telegraf-image
              imagePullPolicy: Never
              name: telegraf-container
              volumeMounts:
              - name: docker-socket
                mountPath: /var/run/docker.sock
            volumes:
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
                type: Socket
