apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf-deployment
    labels:
        type: app
        service: telegraf
spec:
    selector:
        matchLabels:
            type: app
            service: telegraf
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                type: app
                service: telegraf
        spec:
            containers:
            - image: telegraf-image
              imagePullPolicy: Never
              name: telegraf-container
              envFrom:
              - secretRef:
                  name: telegraf-secrets

---

apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb-service:8086
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: admin
