apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    type: app
    service: ftps
spec:
  #replicas: 2
  selector:
    matchLabels:
      type: app
      service: ftps
  template:
    metadata:
      labels:
        type: app
        service: ftps
    spec:
      containers:
      - name: ftps-container
        image: ftps-image
        imagePullPolicy: Never
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          tcpSocket:
            port: 21
        ports:
          - containerPort: 21
            hostPort: 21
          - containerPort: 50000
            hostPort: 50000

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
  labels:
    type: app
    service: ftps
spec:
  type: LoadBalancer
  ports:
    - name: ftps
      port: 21
      protocol: TCP
      targetPort: 21
    - name: passive
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    type: app
    service: ftps

